### ISSUE TITLE
[Future/Question] Fabric support

### ISSUE THREAD

**Issue by MbtMarco** [Xing-C/Classic-and-simple-status-bars#1]
Maybe or not?

**Comment by Xing-C** [comment]
Maybe  this is possible, please tell me your game version

As a beginner, I am not familiar with the development of fabric, which may be a long process.

**Comment by MbtMarco** [comment]
1.20.1 (However I suggest you develop it for 1.20.2 which I assume will be released in a few days ) , i know there're some api that can be helpful to make work Forge mods on Fabric.

**Comment by Xing-C** [comment]
Please tell me 😀

**Comment by MbtMarco** [comment]
Maybe this one: (Library) https://modrinth.com/mod/porting_lib

**Comment by MbtMarco** [comment]
In its github there's also a list of useful api

**Comment by Xing-C** [comment]
I am trying to understand .
In my upstream project, it supports fabric, hesitant.

**Comment by MbtMarco** [comment]
There's no problem, it was just a hypothesis for the future.

**Comment by Xing-C** [comment]
Now supported, please check the link https://modrinth.com/mod/cssb

**Comment by MbtMarco** [comment]
Ty so much, ill test it this afternoon
