### ISSUE TITLE
Crash when entering a boat

### ISSUE THREAD

**Issue by maculator** [Xing-C/Classic-and-simple-status-bars#2]
Cant say for sure its when entering a boat but this is the Exit-Code:-1 (Happend three times when entering a boat. Never happend before adding this mod. Removing this mod solved it 100%, only happens with this mod installed):

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class net.minecraft.class_1690 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1690 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @52aa2946)

This is the Report:

---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-09-20 19:30:22
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_1690 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1690 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @52aa2946)
	at cn.mcxkly.classicandsimplestatusbars.overlays.FoodBar.renderFoodValue(FoodBar.java:110)
	at cn.mcxkly.classicandsimplestatusbars.overlays.FoodBar.render(FoodBar.java:43)
	at net.minecraft.class_329.handler$zmo000$classicandsimplestatusbars$renderHealthBar(class_329.java:4389)
	at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cn.mcxkly.classicandsimplestatusbars.overlays.FoodBar.renderFoodValue(FoodBar.java:110)
	at cn.mcxkly.classicandsimplestatusbars.overlays.FoodBar.render(FoodBar.java:43)
	at net.minecraft.class_329.handler$zmo000$classicandsimplestatusbars$renderHealthBar(class_329.java:4389)
	at net.minecraft.class_329.method_1753(class_329.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['toteskaetzchen'/253, l='ClientLevel', x=5.96, y=62.12, z=2.00]]
	Chunk stats: 16384, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,72,-32), Section: (at 0,8,0 in 0,4,-2; chunk contains blocks 0,-64,-32 to 15,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1586969 game time, 2003534 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/undergrowth-1-0-8-public.zip, seasons:seasonal_lush_caves, file/Gothic+RPG+Font.zip, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1898996496 bytes (1811 MiB) / 4966055936 bytes (4736 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2803
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34760.19
	Virtual memory used (MB): 20308.10
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 4.87
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.2.1
		adorabuild_structures: AdoraBuild: Structures 1.1.0
		advancementframes: advancementframes 1.20-2.1.0
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		advancementplaques: Advancement Plaques 1.4.11
		amethyst_core: Amethyst Core 1.2.2+1.20.1
			common-protection-api: Common Protection API 1.0.0
		amethyst_imbuement: Amethyst Imbuement 1.20.1-10
			conditional-mixin: conditional mixin 0.3.2
			fzzy_config: Fzzy Config 0.1.2+1.20.1
			playerabilitylib: Pal 1.8.0
			structurized-reborn: Structurized Reborn 1.20.1-01
		architectury: Architectury 9.1.12
		artifacts: Artifacts 9.1.0
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.0
			porting_lib_attributes: Porting Lib Attributes 2.1.1093+1.20
				porting_lib_core: Porting Lib Core 2.1.1093+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1093+1.20
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		attributefix: AttributeFix 21.0.2
		autofish: AFKfish 0.1
		axesareweapons: Axes Are Weapons 1.7.1
		betteranimationscollection: Better Animations Collection 8.0.0
		betterarcheology: Better Archeology 1.0.2
		bettercombat: Better Combat 1.7.3+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.1
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.1
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.2
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.1
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.1
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.1
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.1
		biomemusic: Biome Music Mod 1.20.1-2.0
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
			satin: Satin 1.13.0
		bountiful: Bountiful 6.0.3+1.20.1
		castle_dungeons: Castle Dungeons 4.0.0
		cherishedworlds: Cherished Worlds 6.1.2+1.20.1
		classicandsimplestatusbars: Classic and simple status bars 1.0.7
		clickthrough: ClickThrough 1.20-fabric0.83.0-0.4.1
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.4+1.20
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 6.65
		corgilib: CorgiLib 4.0.0.4
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cupboard: cupboard 1.20.1-2.0
		deathlog: DeathLog 0.3.2+1.20
		difficultylock: Difficulty Lock 3.0
		emi: EMI 1.0.19+1.20.1+fabric
		enchantedtooltips: Enchanted ToolTips 1.3.7-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		enhancedcelestials: Enhanced Celestials 5.0.0.2
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		exordium: Exordium 1.2.1-mc1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.2
		explorify: Explorify v1.3.0-mc1.20u1.20.1
		fabric-api: Fabric API 0.88.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.3+92a0d36777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.3+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		fallingtree: FallingTree 4.3.0
		faster_entity_animations: FastAnim 1.6
		forgeconfigapiport: Forge Config API Port 8.0.0
		forgeconfigscreens: Forge Config Screens 8.0.2
		fwaystones: Fabric Waystones 3.1.3+mc1.20
		fzzy_core: Fzzy Core 0.2.7+1.20.1
		gear_core: Gear Core 0.3.3+1.20.1
		gearifiers: Gearifiers 0.4.1+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		gravestones: Gravestones v1.15
		healthindicatortxf: Health Indicator TXF 1.20.1-1.1.2-fabric
		hopobettermineshaft: Hopo Better Mineshaft 1.1.8
		hopobetterruinedportal: Hopo Better Ruined Portal 1.3.6
		hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.1.3
		iceberg: Iceberg 1.1.15
		imbued_gear: Imbued Gear 0.2.1+1.20.1
		indium: Indium 1.0.25+mc1.20.1
		inmis: Inmis 2.7.2-1.20.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		iris: Iris 1.6.8
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.12
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		kambrik: Kambrik 6.1.1+1.20.1
		kiwi: Kiwi Library 11.1.1
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		logcleaner: Log Cleaner 1.0.0
		malilib: MaLiLib 0.16.1
		mcdw: MC Dungeons Weapons 8.0.3
		medievalmusic: Medieval Music Mod 1.20.1-2.1
		minecraft: Minecraft 1.20.1
		minerally: Minerally 1.20.1-0.9.0
		minihud: MiniHUD 0.27.0
		mob_captains_mr: Mob Captains 1-v2.1.2
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.8.21
		moreadvancementsmod: More Advancements Mod 1.3.0-1.20.1
		moreculling: More Culling 1.20.1-0.19.0
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v2.1.4
		no-lan-cheating: No Lan Cheating 1.5.0+1.20.1
		no-shield-delay: No Shield Delay 1.0.0
		no-telemetry: No Telemetry 1.7.0
		owo: oωo 0.11.1+1.20
			blue_endless_jankson: jankson 1.2.2
		patchouli: Patchouli 1.20.1-81-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2-rc1+1.20
		plentyofarmors: Plenty Of Armors 1.3.0
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puzzleslib: Puzzles Lib 8.0.24
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		screenshot_viewer: Screenshot Viewer 1.2.0-fabric-mc1.20
			catconfig-mc: Cat Config MC 0.1.1
				io_github_lgatodu47_catconfig: catconfig 0.2.4
		seasons: Fabric Seasons 2.3+1.20
		snowrealmagic: Snow! Real Magic! 9.0.1
		sodium: Sodium 0.5.2
		spawners_plus: Spawners+ 2.0.1-1.20.1
		starlight: Starlight 1.1.2+fabric.dbc156f
		structory_towers: Structory: Towers 1.0.3
		taxfreelevels: Tax Free Levels 1.3.3
		tooltipfix: ToolTip Fix 1.1.1-1.20
		travelerstitles: Traveler's Titles 1.20-Fabric-4.0.1
		trinkets: Trinkets 3.7.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.1
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: ComplementaryReimagined_r2.3.zip
		Profile: Custom (+28 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.22-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.67, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/undergrowth-1-0-8-public.zip, seasons:seasonal_lush_caves, file/Gothic+RPG+Font.zip, fabric
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['toteskaetzchen'/253, l='ServerLevel[Amethyst Mysteries]', x=5.96, y=62.12, z=2.00]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Xing-C** [comment]
Yes, I will take a look

**Comment by Xing-C** [comment]
Fix crashes caused by vehicle type , Please download the 1.0.8 version of the Mod
