### ISSUE TITLE
Health is always X/20 even if X>20

### ISSUE THREAD

**Issue by maculator** [Xing-C/Classic-and-simple-status-bars#3]
Health bar does not show the real maximum health. Not sure if this is intended or a bug.
Here is a screenshot:
https://i.imgur.com/yGGSDca.jpg
I got 20.5 ouit of 20 health. It should be 20.5/20.5

**Comment by Xing-C** [comment]
Sorry, this part is a bit messy. Some values are set to integers, but others are set by me to retain decimals. This is indeed an error

**Comment by Xing-C** [comment]
I found the problem because the maxhealth is of type int

**Comment by Xing-C** [comment]
![image](https://github.com/Xing-C/Classic-and-simple-status-bars/assets/39401415/e1e8561d-d8f9-4c3c-8d2e-69acbaca6862)

I will upload the new version right away. Now the problem has been solved

**Comment by Xing-C** [comment]
> ![image](https://user-images.githubusercontent.com/39401415/270083361-e1e8561d-d8f9-4c3c-8d2e-69acbaca6862.png)
> 
> I will upload the new version right away. Now the problem has been solved

As shown in the picture, if you remove the Coleoptera equipment, the health column will display 20/20, which is for correct display, but the real data, the health value is still 25.9/20. If you find it, I just want to say it is not a bug

**Comment by Xing-C** [comment]
I found that the type of vanilla armor value and armor toughness is an integer, so the decimal point is not displayed. Even the armor value of 1.8 will be displayed as 1 armor.

/give @s minecraft:elytra{AttributeModifiers:[{AttributeName:"generic.armor",Operation:0,Amount:1.9d,Slot:"chest",Name:"Armor",UUID:[I;1,2,3,4]}, {AttributeName:"generic.max_health",Operation:0,Amount:1.9d,Slot:"chest",Name:"MaxHealth",UUID:[I;1,2,3,5]}]}

![image](https://github.com/Xing-C/Classic-and-simple-status-bars/assets/39401415/e4874a32-6935-4530-b9a5-c008c215b11e)

**Comment by Xing-C** [comment]
Use v1.0.9

**Comment by maculator** [comment]
It works, thank you, good mod!

**Comment by Xing-C** [comment]
> It works, thank you, good mod!

You're welcome, this is what I should do. I hope it's perfect
